https://pubmed.ncbi.nlm.nih.gov/25516601/
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE61333

```{r}
install.packages("BiocManager")

BiocManager::install("WGCNA")
```
```{r}
library(magrittr)
library(tidyverse)
```

```{r}
install.packages("fastmap")
```

```{r}
library(WGCNA)
```

```{r}
data <- readr::read_delim("GSE61333_ligule_count.txt",     # <= path to the data file
                          delim = "\t")
```

```{r}
col_sel <- names(data)[-1]
col_sel
```
```{r}
mdata <- data %>% tidyr::pivot_longer(., all_of(col_sel)) %>% mutate(group = gsub("-.*","", name) %>% gsub("[.].*","", .))

```

```{r}
p <- mdata %>% ggplot(., aes(x=name , y=value )) +
  geom_violin() +
  geom_point() + 
  labs(x = "Treatment Groups", y= "RNA Seq Counts") +
  facet_grid(cols = vars(group), scales = "free_x")
p 
```
# Normalize the counts
```{r}
library(DESeq2)
```

```{r}
# DESeq's input is a matrix of integers
de_input <- as.matrix(data[, -1])
rownames(de_input) <- data$Count
de_input[1:5, 1:10]
```
```{r}
meta_df <- data.frame(Sample = names(data[-1])) %>%
  mutate(
    Type = gsub("-.*","", Sample) %>% gsub("[.].*","", .)
  )
```

```{r}
dds <- DESeqDataSetFromMatrix(round(de_input), meta_df, design = ~Type)
```

```{r}
dds <- DESeq(dds)
```
```{r}
vst <- varianceStabilizingTransformation(dds)
```

```{r}
wpn_vsd <- getVarianceStabilizedData(dds)
rv_wpn <- rowVars(wpn_vsd)
summary(rv_wpn)
```


```{r}
q75_wpn <- quantile( rowVars(wpn_vsd), .75)  # <= original
q95_wpn <- quantile( rowVars(wpn_vsd), .95)  # <= changed to 95 quantile to reduce dataset
expr_normalized <- wpn_vsd[ rv_wpn > q95_wpn, ]
```

```{r}
expr_normalized[1:5,1:10]
```

```{r}
expr_normalized_df <- data.frame(expr_normalized) %>% mutate(Gene_id = row.names(expr_normalized)) %>% 
   pivot_longer(-Gene_id)
```

```{r}
expr_normalized_df %>% ggplot(., aes(x = name, y = value)) +
  geom_violin() +
  geom_point() +
  theme_bw() +
  theme(
    axis.text.x = element_text( angle = 90)
  ) +
  ylim(0, NA) +
  labs(
    title = "Normalized and 95 quantile Expression",
    x = "treatment",
    y = "normalized expression"
  )
```
# WGCNA

```{r}
input_mat <- t(expr_normalized)
input_mat[1:5, 1:10]
```

```{r}
powers = c(c(1:10), seq(from = 12, to = 20, by = 2))

# Network topology analysis function
sft = pickSoftThreshold(input_mat, powerVector = powers, verbose = 5)
```
```{r}
par(mfrow = c(1,2));
cex1 = 0.9;

plot(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     xlab = "Soft Threshold (power)",
     ylab = "Scale Free Topology Model Fit, signed R^2",
     main = paste("Scale independence")
)
text(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     labels = powers, cex = cex1, col = "red"
)
abline(h = 0.90, col = "red")
plot(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     xlab = "Soft Threshold (power)",
     ylab = "Mean Connectivity",
     type = "n",
     main = paste("Mean connectivity")
)
text(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     labels = powers,
     cex = cex1, col = "red")
```
```{r}
picked_power = 9
temp_cor <- cor       
cor <- WGCNA::cor    
netwk <- blockwiseModules(input_mat, power = picked_power, networkType = "signed", deepSplit = 2,
                          pamRespectsDendro = F,  minModuleSize = 30,
                          maxBlockSize = 4000, reassignThreshold = 0,
                          mergeCutHeight = 0.25,  saveTOMs = T,
                          saveTOMFileBase = "ER", numericLabels = T,
                          verbose = 3)
```

```{r}
cor <- temp_cor  
```

```{r}
# Convert labels to colors for plotting
mergedColors = labels2colors(netwk$colors)
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(
  netwk$dendrograms[[1]],
  mergedColors[netwk$blockGenes[[1]]],
  "Module colors",
  dendroLabels = FALSE,
  hang = 0.03,
  addGuide = TRUE,
  guideHang = 0.05 )

```
# Relate Module (cluster) Assignments to Treatment Groups

```{r}
module_df <- data.frame(
  gene_id = names(netwk$colors),
  colors = labels2colors(netwk$colors)
)

module_df[1:5,]
#>            gene_id    colors
#> 1 AC149818.2_FG001      blue
#> 2 AC149829.2_FG003      blue
#> 3 AC182617.3_FG001      blue
#> 4 AC186512.3_FG001 turquoise
#> 5 AC186512.3_FG007 turquoise

write_delim(module_df,
            file = "gene_modules.txt",
            delim = "\t")

```
```{r}
# Get Module Eigengenes per cluster
MEs0 <- moduleEigengenes(input_mat, mergedColors)$eigengenes

# Reorder modules so similar modules are next to each other
MEs0 <- orderMEs(MEs0)
module_order = names(MEs0) %>% gsub("ME","", .)

# Add treatment names
MEs0$treatment = row.names(MEs0)

# tidy & plot data
mME = MEs0 %>%
  pivot_longer(-treatment) %>%
  mutate(
    name = gsub("ME", "", name),
    name = factor(name, levels = module_order)
  )

mME %>% ggplot(., aes(x=treatment, y=name, fill=value)) +
  geom_tile() +
  theme_bw() +
  scale_fill_gradient2(
    low = "blue",
    high = "red",
    mid = "white",
    midpoint = 0,
    limit = c(-1,1)) +
  theme(axis.text.x = element_text(angle=90)) +
  labs(title = "Module-trait Relationships", y = "Modules", fill="corr")

```

```{r}
# pick out a few modules of interest here
modules_of_interest = c("green", "turquoise", "tan")

# Pull out list of genes in that module
submod = module_df %>%
  subset(colors %in% modules_of_interest)

row.names(module_df) = module_df$gene_id

# Get normalized expression for those genes
expr_normalized[1:5,1:10]
```
```{r}
subexpr = expr_normalized[submod$gene_id,]

submod_df = data.frame(subexpr) %>%
  mutate(
    gene_id = row.names(.)
  ) %>%
  pivot_longer(-gene_id) %>%
  mutate(
    module = module_df[gene_id,]$colors
  )

submod_df %>% ggplot(., aes(x=name, y=value, group=gene_id)) +
  geom_line(aes(color = module),
            alpha = 0.2) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90)
  ) +
  facet_grid(rows = vars(module)) +
  labs(x = "treatment",
       y = "normalized expression")
```
```{r}
genes_of_interest = module_df %>%
  subset(colors %in% modules_of_interest)

expr_of_interest = expr_normalized[genes_of_interest$gene_id,]
expr_of_interest[1:5,1:5]
```
```{r}
TOM = TOMsimilarityFromExpr(t(expr_of_interest),
                            power = picked_power)
```

```{r}
# Add gene names to row and columns
row.names(TOM) = row.names(expr_of_interest)
colnames(TOM) = row.names(expr_of_interest)

edge_list = data.frame(TOM) %>%
  mutate(
    gene1 = row.names(.)
  ) %>%
  pivot_longer(-gene1) %>%
  dplyr::rename(gene2 = name, correlation = value) %>%
  unique() %>%
  subset(!(gene1==gene2)) %>%
  mutate(
    module1 = module_df[gene1,]$colors,
    module2 = module_df[gene2,]$colors
  )
```

```{r}
# Export Network file to be read into Cytoscape, VisANT, etc
write_delim(edge_list,
            file = "edgelist.tsv",
            delim = "\t")
```

